### ISSUE TITLE
Incorrect handle of not-exist ssh in db

### ISSUE THREAD

**Issue by esikachev** [esikachev/my-dev-server#44]
Steps:
Try to get not-exist user and ssh from db in ssh_get

Actual result in logs of my-dev-server:
```[2017-01-24 23:37:30,026] ERROR in app: Exception on /users/50/ssh/host [GET]
Traceback (most recent call last):
  File "/Users/esikachev/my-dev-server/.tox/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/esikachev/my-dev-server/.tox/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/esikachev/my-dev-server/.tox/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/esikachev/my-dev-server/.tox/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/esikachev/my-dev-server/.tox/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/esikachev/my-dev-server/my_dev_server/server/main.py", line 129, in ssh_get
    return jsonify(ssh_by_id.to_json())
AttributeError: 'NoneType' object has no attribute 'to_json'```

**Comment by esikachev** [comment]
closed in #54
